version: '2'

services:

  teamcity:
    image: jetbrains/teamcity-server
    ports:
      - ${PORT}:8111
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    links:
      - mysql

  mysql:
    image: mysql
    volumes:
      - tc_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  tc_mysql: